//! Bounded, deterministic validation scenarios for the depth mechanics.
//!
//! This module deliberately drives the public [`bw_sim::World`] command and
//! tick API.  It does not reproduce combat, movement, or economy rules.  The
//! small fixtures use existing tick-zero entities with consistent public
//! state, then record every meaningful transition through normal commands.

use bw_content::{
    self, DOCTRINE_PRESSURE, DOCTRINE_SALVAGE, DOCTRINE_TICKS, Doctrine, LOOM_BLAST_RADIUS,
    LOOM_WINDUP_TICKS, SURGE_COOLDOWN_TICKS, SURGE_PRESSURE, SURGE_TICKS, spec,
};
use bw_core::{FP, Faction, Kind, Pos, TICK_HZ};
use bw_sim::{Command, Entity, Event, EventKind, Formation, Order, World};
use serde_json::{Map, Value, json};
use std::fs;
use std::path::Path;
// Only the macOS machine label shells out; elsewhere the import is unused.
#[cfg(target_os = "macos")]
use std::process::Command as ProcessCommand;
use std::time::Instant;

const CROWD_ENTITY_COUNT: usize = 128;
const SCENARIO_TICK_LIMIT: u64 = 5_000;
const SAVE_RESUME_TICKS: u32 = 90;
const SURGE_POST_ACTIVE_TICKS: u32 = 12;

/// Run the complete bounded depth suite and write one JSON report plus the
/// replay/save files generated by each scenario.
pub fn run(out: &Path) -> Result<(), String> {
    fs::create_dir_all(out).map_err(|error| format!("create depth output: {error}"))?;

    let mut scenarios = Map::new();
    let mut failures = Vec::new();
    record(
        &mut scenarios,
        &mut failures,
        "loom_stationary_vs_dodge",
        loom_stationary_vs_dodge(out),
    );
    record(
        &mut scenarios,
        &mut failures,
        "loom_clustered_vs_spread",
        loom_clustered_vs_spread(out),
    );
    record(
        &mut scenarios,
        &mut failures,
        "bulwark_front_vs_rear",
        bulwark_front_vs_rear(out),
    );
    record(
        &mut scenarios,
        &mut failures,
        "formation_and_facing",
        formation_and_facing(out),
    );
    record(
        &mut scenarios,
        &mut failures,
        "surge_movement_cost_and_fire_lock",
        surge_movement_cost_and_fire_lock(out),
    );
    record(
        &mut scenarios,
        &mut failures,
        "research_union_hauling",
        doctrine_research(out, Faction::Union, Doctrine::Hauling),
    );
    record(
        &mut scenarios,
        &mut failures,
        "research_assembly_fire_control",
        doctrine_research(out, Faction::Assembly, Doctrine::FireControl),
    );
    record(
        &mut scenarios,
        &mut failures,
        "crowd_128_tick_benchmark",
        crowd_128_benchmark(out),
    );

    let report = json!({
        "schema": "brinewake-depth-check-v1",
        "rules_version": bw_content::RULES_VERSION,
        "sim_version": bw_sim::SIM_VERSION,
        "scenarios": scenarios,
        "failure_count": failures.len(),
        "failures": failures,
        "evidence_limits": "Controlled simulation evidence only. These checks demonstrate implementation behavior and deterministic replay; they are not human fun, clarity, balance, pacing, final art, or minimum-hardware approval.",
    });
    let report_path = out.join("depth-report.json");
    fs::write(
        &report_path,
        serde_json::to_vec_pretty(&report)
            .map_err(|error| format!("serialize depth report: {error}"))?,
    )
    .map_err(|error| format!("write depth report: {error}"))?;
    println!(
        "{}",
        serde_json::to_string_pretty(&report).unwrap_or_default()
    );

    if failures.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "depth-check reported {} failed scenario(s); see {}",
            failures.len(),
            report_path.display()
        ))
    }
}

fn record(
    scenarios: &mut Map<String, Value>,
    failures: &mut Vec<String>,
    name: &str,
    result: Result<Value, String>,
) {
    match result {
        Ok(value) => {
            scenarios.insert(name.to_string(), value);
        }
        Err(error) => {
            failures.push(format!("{name}: {error}"));
            scenarios.insert(
                name.to_string(),
                json!({"status": "failed", "error": error}),
            );
        }
    }
}

fn base_world(seed: u64, faction: Faction) -> World {
    let mut world = World::new(seed, faction);
    world.ai_enabled = false;
    for entity in &mut world.entities {
        entity.order = Order::Idle;
        entity.path.clear();
        entity.path_index = 0;
        entity.path_target = None;
        entity.waypoints.clear();
        entity.gather_ticks = 0;
        entity.carried = 0;
        entity.carried_kind = None;
        entity.surge_remaining = 0;
        entity.surge_cooldown = 0;
        entity.formation = Formation::Compact;
    }
    // Keep the authored tick-zero normalization as the replay origin.  The
    // public helper rejects any accidental pending input or advanced tick.
    world
        .reset_fixture_origin()
        .expect("clean depth fixture should rebase successfully");
    world
}

fn ids_for(world: &World, owner: u8, kind: Kind) -> Vec<u32> {
    world
        .entities
        .iter()
        .filter(|entity| entity.owner == owner && entity.kind == kind && entity.hp > 0)
        .map(|entity| entity.id)
        .collect()
}

fn first_id(world: &World, owner: u8, kind: Kind) -> Result<u32, String> {
    ids_for(world, owner, kind)
        .into_iter()
        .next()
        .ok_or_else(|| format!("missing player {owner} {} fixture entity", kind.name()))
}

fn entity(world: &World, id: u32) -> Result<&Entity, String> {
    world
        .entities
        .iter()
        .find(|item| item.id == id && item.hp > 0)
        .ok_or_else(|| format!("fixture entity {id} is missing or dead"))
}

/// Convert one existing tick-zero machine to a specialist/combat role while
/// keeping its serialized fields coherent.  Entity IDs stay unique and
/// monotonic because no entity is inserted or removed before the first input.
fn transform_entity(world: &mut World, id: u32, kind: Kind, pos: Pos) -> Result<(), String> {
    let (owner, old_kind) = {
        let current = entity(world, id)?;
        (current.owner, current.kind)
    };
    let old_crew = spec(old_kind).crew;
    let new_spec = spec(kind);
    if old_kind != kind {
        world.players[owner as usize].crew = world.players[owner as usize]
            .crew
            .saturating_sub(old_crew)
            .saturating_add(new_spec.crew);
    }
    let current = world
        .entities
        .iter_mut()
        .find(|item| item.id == id)
        .ok_or_else(|| format!("fixture entity {id} disappeared"))?;
    current.kind = kind;
    current.pos = pos;
    current.hp = new_spec.health;
    current.max_hp = new_spec.health;
    current.facing = if owner == 0 { 0 } else { 4 };
    current.build_remaining = 0;
    current.queue.clear();
    current.deployed = false;
    current.deploy_remaining = 0;
    current.deploy_target = false;
    current.formation = Formation::Compact;
    current.surge_remaining = 0;
    current.surge_cooldown = 0;
    current.order = Order::Idle;
    current.carried = 0;
    current.carried_kind = None;
    current.gather_ticks = 0;
    current.attack_cooldown = 0;
    current.path.clear();
    current.path_index = 0;
    current.path_target = None;
    current.blocked_ticks = 0;
    current.waypoints.clear();
    current.rally = None;
    current.builder = None;
    current.last_seen = None;
    Ok(())
}

fn place_entity(world: &mut World, id: u32, pos: Pos, order: Order) -> Result<(), String> {
    let current = world
        .entities
        .iter_mut()
        .find(|item| item.id == id)
        .ok_or_else(|| format!("fixture entity {id} disappeared"))?;
    current.pos = pos;
    current.order = order;
    current.path.clear();
    current.path_index = 0;
    current.path_target = None;
    current.waypoints.clear();
    Ok(())
}

fn issue_step(world: &mut World, player: u8, command: Command) -> Result<(), String> {
    let description = format!("{command:?}");
    world
        .issue(player, command)
        .map_err(|error| format!("issue {description}: {error}"))?;
    world.step();
    Ok(())
}

fn step_until<F>(world: &mut World, limit: u64, mut done: F) -> Result<(), String>
where
    F: FnMut(&World) -> bool,
{
    for _ in 0..limit {
        if done(world) {
            return Ok(());
        }
        world.step();
    }
    if done(world) {
        Ok(())
    } else {
        Err(format!(
            "condition did not settle within {limit} ticks at {}",
            world.tick
        ))
    }
}

fn event(world: &World, kind: EventKind, entity_id: Option<u32>) -> Option<&Event> {
    world
        .events
        .iter()
        .find(|item| item.kind == kind && entity_id.is_none_or(|id| item.entity == Some(id)))
}

fn damage_events(world: &World, target_ids: &[u32]) -> Vec<Event> {
    world
        .events
        .iter()
        .filter(|item| item.kind == EventKind::Damage)
        .filter(|item| item.entity.is_some_and(|id| target_ids.contains(&id)))
        .cloned()
        .collect()
}

fn replay_evidence(world: &mut World, out: &Path, name: &str) -> Result<Value, String> {
    let path = out.join(name);
    world
        .export_replay(&path)
        .map_err(|error| format!("export {}: {error}", path.display()))?;
    let expected = world.state_hash();
    let replayed =
        World::replay(&path).map_err(|error| format!("replay {}: {error}", path.display()))?;
    let actual = replayed.state_hash();
    if expected != actual {
        return Err(format!(
            "replay hash mismatch for {}: expected {expected}, got {actual}",
            path.display()
        ));
    }
    Ok(json!({
        "path": path.display().to_string(),
        "tick": world.tick,
        "final_hash": expected,
        "replay_hash": actual,
        "command_count": world.command_log.len(),
    }))
}

fn save_resume_evidence(world: &mut World, out: &Path, name: &str) -> Result<Value, String> {
    let path = out.join(name);
    world
        .save(&path)
        .map_err(|error| format!("save {}: {error}", path.display()))?;
    let mut loaded =
        World::load(&path).map_err(|error| format!("load {}: {error}", path.display()))?;
    let start_hash = world.state_hash();
    if start_hash != loaded.state_hash() {
        return Err(format!("save hash mismatch at {}", world.tick));
    }
    for _ in 0..SAVE_RESUME_TICKS {
        world.step();
        loaded.step();
        if world.state_hash() != loaded.state_hash() {
            return Err(format!("save/resume diverged at tick {}", world.tick));
        }
    }
    Ok(json!({
        "path": path.display().to_string(),
        "start_tick": world.tick.saturating_sub(u64::from(SAVE_RESUME_TICKS)),
        "resume_ticks": SAVE_RESUME_TICKS,
        "resumed_hash": world.state_hash(),
    }))
}

fn loom_fixture(seed: u64) -> Result<(World, u32, Vec<u32>), String> {
    let mut world = base_world(seed, Faction::Assembly);
    let loom = first_id(&world, 0, Kind::Wick)?;
    transform_entity(&mut world, loom, Kind::Loom, Pos::cell(96, 64))?;
    let targets = ids_for(&world, 1, Kind::Hook);
    if targets.len() < 2 {
        return Err("loom fixture needs two enemy workers".to_string());
    }
    for id in &targets {
        place_entity(&mut world, *id, Pos::cell(115, 112), Order::Idle)?;
    }
    world.reset_fixture_origin()?;
    Ok((world, loom, targets))
}

fn deploy_loom(world: &mut World, loom: u32) -> Result<(), String> {
    issue_step(world, 0, Command::Deploy { units: vec![loom] })?;
    step_until(world, TICK_HZ * 3, |current| {
        entity(current, loom).is_ok_and(|item| item.deployed && item.deploy_remaining == 0)
    })?;
    // A freshly deployed Loom is allowed to acquire visible targets through
    // its normal `Deploy` order.  Stop it for one deterministic tick so the
    // scenario's explicit Attack command is the shot under measurement.
    issue_step(world, 0, Command::Stop { units: vec![loom] })
}

fn move_entity_to(world: &mut World, player: u8, id: u32, target: Pos) -> Result<(), String> {
    issue_step(
        world,
        player,
        Command::Move {
            units: vec![id],
            target,
            queued: false,
        },
    )?;
    step_until(world, SCENARIO_TICK_LIMIT, |current| {
        entity(current, id).is_ok_and(|item| item.pos == target)
    })
}

fn launch_loom(world: &mut World, loom: u32, target: u32) -> Result<(u64, u64), String> {
    if !world.visible(0, entity(world, target)?.pos) {
        return Err("loom target is not visible at launch".to_string());
    }
    issue_step(
        world,
        0,
        Command::Attack {
            units: vec![loom],
            target,
        },
    )?;
    // Idle machines engage on their own, so a deployed Loom may already be
    // cooling from a shot of its own choosing.  The measured shot is the next
    // warning it emits; the window covers one full cooldown.
    step_until(world, 120, |current| {
        event(current, EventKind::ArtilleryWarning, Some(loom)).is_some()
    })
    .map_err(|_| "loom launch emitted no ArtilleryWarning within 120 ticks".to_string())?;
    let warning = event(world, EventKind::ArtilleryWarning, Some(loom))
        .map(|item| item.tick)
        .ok_or_else(|| "loom launch emitted no ArtilleryWarning".to_string())?;
    let shot = world
        .artillery
        .iter()
        .find(|item| item.source == loom)
        .ok_or_else(|| "loom launch emitted no public ArtilleryShot".to_string())?;
    let expected = u64::from(LOOM_WINDUP_TICKS);
    if shot.impact_tick.saturating_sub(warning) != expected {
        return Err(format!(
            "loom windup mismatch: warning {warning}, impact {}, expected {expected}",
            shot.impact_tick
        ));
    }
    Ok((warning, shot.impact_tick))
}

fn wait_for_loom_impact(
    world: &mut World,
    targets: &[u32],
    impact_tick: u64,
) -> Result<Vec<Event>, String> {
    let limit = impact_tick.saturating_sub(world.tick).saturating_add(12);
    let mut impacts = Vec::new();
    for _ in 0..limit {
        world.step();
        impacts.extend(damage_events(world, targets));
        if world.tick > impact_tick && !impacts.is_empty() {
            break;
        }
    }
    Ok(impacts)
}

fn loom_stationary_vs_dodge(out: &Path) -> Result<Value, String> {
    // The target walks into place before the Loom deploys: an undeployed Loom
    // neither fires nor pursues, so the measured shot is the first one.
    let (mut stationary, stationary_loom, stationary_targets) = loom_fixture(4101)?;
    move_entity_to(
        &mut stationary,
        1,
        stationary_targets[0],
        Pos::cell(103, 64),
    )?;
    deploy_loom(&mut stationary, stationary_loom)?;
    let (stationary_warning_tick, stationary_impact_tick) =
        launch_loom(&mut stationary, stationary_loom, stationary_targets[0])?;
    let stationary_impacts = wait_for_loom_impact(
        &mut stationary,
        &[stationary_targets[0]],
        stationary_impact_tick,
    )?;
    if stationary_impacts.is_empty() {
        return Err("stationary Loom target escaped or was not impacted".to_string());
    }
    let stationary_damage: i32 = stationary_impacts.iter().map(|item| item.amount).sum();
    let stationary_hp = entity(&stationary, stationary_targets[0])?.hp;
    let stationary_replay =
        replay_evidence(&mut stationary, out, "loom-stationary-assembly.replay.json")?;

    let (mut dodging, dodging_loom, dodging_targets) = loom_fixture(4101)?;
    move_entity_to(&mut dodging, 1, dodging_targets[0], Pos::cell(103, 64))?;
    deploy_loom(&mut dodging, dodging_loom)?;
    let (dodging_warning_tick, dodging_impact_tick) =
        launch_loom(&mut dodging, dodging_loom, dodging_targets[0])?;
    move_entity_to(&mut dodging, 1, dodging_targets[0], Pos::cell(112, 64))?;
    let dodging_impacts =
        wait_for_loom_impact(&mut dodging, &[dodging_targets[0]], dodging_impact_tick)?;
    let dodging_damage: i32 = dodging_impacts.iter().map(|item| item.amount).sum();
    let dodging_hp = entity(&dodging, dodging_targets[0])?.hp;
    let dodging_replay = replay_evidence(&mut dodging, out, "loom-dodge-assembly.replay.json")?;
    if stationary_damage <= dodging_damage {
        return Err(format!(
            "stationary target did not take more damage: stationary={stationary_damage}, dodge={dodging_damage}"
        ));
    }
    Ok(json!({
        "status": "passed",
        "faction": "Assembly",
        "loom_windup_ticks": LOOM_WINDUP_TICKS,
        "warning_to_impact_ticks": stationary_impact_tick.saturating_sub(stationary_warning_tick),
        "dodge_warning_to_impact_ticks": dodging_impact_tick.saturating_sub(dodging_warning_tick),
        "stationary": {"damage": stationary_damage, "hp_after": stationary_hp, "replay": stationary_replay},
        "dodging": {"damage": dodging_damage, "hp_after": dodging_hp, "replay": dodging_replay},
        "interpretation": "The marked ground point remains fixed while a target that leaves the blast area takes less damage.",
    }))
}

fn loom_clustered_vs_spread(out: &Path) -> Result<Value, String> {
    let run_layout =
        |seed: u64, clustered: bool| -> Result<(World, i32, usize, Value, [u32; 2]), String> {
            let (mut world, loom, targets) = loom_fixture(seed)?;
            let second = if clustered {
                Pos::cell(104, 64)
            } else {
                Pos::cell(108, 64)
            };
            move_entity_to(&mut world, 1, targets[0], Pos::cell(103, 64))?;
            move_entity_to(&mut world, 1, targets[1], second)?;
            deploy_loom(&mut world, loom)?;
            let (_, impact_tick) = launch_loom(&mut world, loom, targets[0])?;
            let impacts = wait_for_loom_impact(&mut world, &targets[..2], impact_tick)?;
            if impacts.is_empty() {
                return Err("Loom blast did not produce any damage events".to_string());
            }
            let damage: i32 = impacts.iter().map(|item| item.amount).sum();
            let affected = impacts
                .iter()
                .filter_map(|item| item.entity)
                .collect::<std::collections::BTreeSet<_>>()
                .len();
            let replay = replay_evidence(
                &mut world,
                out,
                if clustered {
                    "loom-clustered-assembly.replay.json"
                } else {
                    "loom-spread-assembly.replay.json"
                },
            )?;
            Ok((world, damage, affected, replay, [targets[0], targets[1]]))
        };
    let (clustered_world, clustered_damage, clustered_affected, clustered_replay, clustered_ids) =
        run_layout(4102, true)?;
    let (spread_world, spread_damage, spread_affected, spread_replay, spread_ids) =
        run_layout(4102, false)?;
    let clustered_hp = [
        entity(&clustered_world, clustered_ids[0])?.hp,
        entity(&clustered_world, clustered_ids[1])?.hp,
    ];
    let spread_hp = [
        entity(&spread_world, spread_ids[0])?.hp,
        entity(&spread_world, spread_ids[1])?.hp,
    ];
    if clustered_damage <= spread_damage || clustered_affected <= spread_affected {
        return Err(format!(
            "clustered blast did not affect more targets/damage: clustered={clustered_damage}/{clustered_affected}, spread={spread_damage}/{spread_affected}"
        ));
    }
    Ok(json!({
        "status": "passed",
        "blast_radius_fixed_point": LOOM_BLAST_RADIUS,
        "clustered": {"damage": clustered_damage, "affected_targets": clustered_affected, "hp_after": clustered_hp, "replay": clustered_replay},
        "spread": {"damage": spread_damage, "affected_targets": spread_affected, "hp_after": spread_hp, "replay": spread_replay},
        "interpretation": "Two targets inside the 1.25-cell blast overlap; three-cell separation limits the impact to the marked target.",
    }))
}

fn bulwark_damage(out: &Path, front: bool, replay_name: &str) -> Result<(i32, Value), String> {
    let mut world = base_world(4200 + u64::from(front), Faction::Union);
    let bulwark = first_id(&world, 0, Kind::Hook)?;
    transform_entity(&mut world, bulwark, Kind::Bulwark, Pos::cell(96, 64))?;
    let attacker = first_id(&world, 1, Kind::Wick)?;
    transform_entity(
        &mut world,
        attacker,
        Kind::Reedguard,
        if front {
            Pos::cell(100, 64)
        } else {
            Pos::cell(92, 64)
        },
    )?;
    for id in ids_for(&world, 1, Kind::Wick) {
        place_entity(&mut world, id, Pos::cell(115, 112), Order::Idle)?;
    }
    world.reset_fixture_origin()?;
    issue_step(
        &mut world,
        0,
        Command::Face {
            units: vec![bulwark],
            target: Pos::cell(104, 64),
        },
    )?;
    let facing = entity(&world, bulwark)?.facing;
    issue_step(
        &mut world,
        0,
        Command::Deploy {
            units: vec![bulwark],
        },
    )?;
    step_until(&mut world, TICK_HZ * 3, |current| {
        entity(current, bulwark).is_ok_and(|item| item.deployed)
    })?;
    issue_step(
        &mut world,
        1,
        Command::Attack {
            units: vec![attacker],
            target: bulwark,
        },
    )?;
    // The attacker may have fired from idle already and be cooling; the
    // measured hit is the next one it lands.
    step_until(&mut world, 120, |current| {
        event(current, EventKind::Damage, Some(bulwark)).is_some()
    })
    .map_err(|_| "Bulwark fixture produced no incoming damage within 120 ticks".to_string())?;
    let damage = event(&world, EventKind::Damage, Some(bulwark))
        .map(|item| item.amount)
        .ok_or_else(|| "Bulwark fixture produced no incoming damage".to_string())?;
    let replay = replay_evidence(&mut world, out, replay_name)?;
    Ok((
        damage,
        json!({"facing": facing, "damage": damage, "replay": replay}),
    ))
}

fn bulwark_front_vs_rear(out: &Path) -> Result<Value, String> {
    let (front_damage, front) = bulwark_damage(out, true, "bulwark-front-union.replay.json")?;
    let (rear_damage, rear) = bulwark_damage(out, false, "bulwark-rear-union.replay.json")?;
    if rear_damage <= front_damage {
        return Err(format!(
            "rear Bulwark damage was not greater than front: front={front_damage}, rear={rear_damage}"
        ));
    }
    Ok(json!({
        "status": "passed",
        "front": front,
        "rear": rear,
        "front_damage": front_damage,
        "rear_damage": rear_damage,
        "interpretation": "The deployed Bulwark keeps its face and halves incoming damage from its forward half-plane.",
    }))
}

fn formation_and_facing(out: &Path) -> Result<Value, String> {
    let mut world = base_world(4300, Faction::Union);
    let mut units = ids_for(&world, 0, Kind::Hook);
    if units.len() < 2 {
        return Err("formation fixture needs two starting units".to_string());
    }
    units.truncate(2);
    for (index, id) in units.iter().enumerate() {
        transform_entity(
            &mut world,
            *id,
            Kind::Riveter,
            Pos::cell(20 + index as i32, 110),
        )?;
    }
    let initial_facing = units
        .iter()
        .map(|id| entity(&world, *id).map(|item| item.facing))
        .collect::<Result<Vec<_>, _>>()?;
    world.reset_fixture_origin()?;
    issue_step(
        &mut world,
        0,
        Command::SetFormation {
            units: units.clone(),
            formation: Formation::Loose,
        },
    )?;
    issue_step(
        &mut world,
        0,
        Command::Move {
            units: units.clone(),
            target: Pos::cell(40, 110),
            queued: false,
        },
    )?;
    let loose_targets = units
        .iter()
        .map(|id| order_target(&world, *id))
        .collect::<Result<Vec<_>, _>>()?;
    issue_step(
        &mut world,
        0,
        Command::SetFormation {
            units: units.clone(),
            formation: Formation::Line,
        },
    )?;
    issue_step(
        &mut world,
        0,
        Command::Move {
            units: units.clone(),
            target: Pos::cell(55, 110),
            queued: false,
        },
    )?;
    let line_targets = units
        .iter()
        .map(|id| order_target(&world, *id))
        .collect::<Result<Vec<_>, _>>()?;
    let face_targets = units
        .iter()
        .map(|id| {
            let current = entity(&world, *id)?;
            Ok((
                *id,
                Pos::raw(current.pos.x.saturating_add(5 * FP), current.pos.y),
            ))
        })
        .collect::<Result<Vec<_>, String>>()?;
    for (id, target) in face_targets {
        issue_step(
            &mut world,
            0,
            Command::Face {
                units: vec![id],
                target,
            },
        )?;
    }
    let faced = units
        .iter()
        .map(|id| entity(&world, *id).map(|item| item.facing))
        .collect::<Result<Vec<_>, _>>()?;
    let face_stopped = units.iter().all(|id| {
        entity(&world, *id).is_ok_and(|item| {
            matches!(item.order, Order::Idle) && item.path.is_empty() && item.path_target.is_none()
        })
    });
    let loose_span = span_cells(&loose_targets);
    let line_span = span_cells(&line_targets);
    if loose_span <= 1
        || line_span == 0
        || !face_stopped
        || faced.windows(2).any(|pair| pair[0] != pair[1])
        || faced == initial_facing
    {
        return Err(format!(
            "formation offsets or Face turn/stop were not observable: loose={loose_span}, line={line_span}, initial={initial_facing:?}, faced={faced:?}, stopped={face_stopped}"
        ));
    }
    let replay = replay_evidence(&mut world, out, "formation-line-loose-union.replay.json")?;
    Ok(json!({
        "status": "passed",
        "unit_ids": units,
        "loose_targets": loose_targets,
        "line_targets": line_targets,
        "faced_directions": faced,
        "face_stopped": face_stopped,
        "loose_span_cells": loose_span,
        "line_span_cells": line_span,
        "replay": replay,
        "interpretation": "Formation is stored on units and changes subsequent destination slots deterministically by sorted entity ID.",
    }))
}

fn order_target(world: &World, id: u32) -> Result<Pos, String> {
    match &entity(world, id)?.order {
        Order::Move { target } | Order::AttackMove { target } => Ok(*target),
        order => Err(format!("unit {id} has unexpected order {order:?}")),
    }
}

fn span_cells(positions: &[Pos]) -> i32 {
    let min_x = positions
        .iter()
        .map(|pos| pos.cell_xy().0)
        .min()
        .unwrap_or(0);
    let max_x = positions
        .iter()
        .map(|pos| pos.cell_xy().0)
        .max()
        .unwrap_or(0);
    let min_y = positions
        .iter()
        .map(|pos| pos.cell_xy().1)
        .min()
        .unwrap_or(0);
    let max_y = positions
        .iter()
        .map(|pos| pos.cell_xy().1)
        .max()
        .unwrap_or(0);
    (max_x - min_x).max(max_y - min_y)
}

fn surge_movement_cost_and_fire_lock(out: &Path) -> Result<Value, String> {
    let make_movement_world = |seed: u64| -> Result<(World, u32), String> {
        let mut world = base_world(seed, Faction::Union);
        let unit = first_id(&world, 0, Kind::Hook)?;
        transform_entity(&mut world, unit, Kind::Riveter, Pos::cell(20, 110))?;
        world.reset_fixture_origin()?;
        Ok((world, unit))
    };
    let (mut control, control_unit) = make_movement_world(4401)?;
    let (mut surged, surged_unit) = make_movement_world(4401)?;
    let control_start = entity(&control, control_unit)?.pos;
    let surged_start = entity(&surged, surged_unit)?.pos;
    control
        .issue(
            0,
            Command::Move {
                units: vec![control_unit],
                target: Pos::cell(50, 110),
                queued: false,
            },
        )
        .map_err(|error| format!("control movement: {error}"))?;
    surged
        .issue(
            0,
            Command::Surge {
                units: vec![surged_unit],
            },
        )
        .map_err(|error| format!("Surge activation: {error}"))?;
    surged
        .issue(
            0,
            Command::Move {
                units: vec![surged_unit],
                target: Pos::cell(50, 110),
                queued: false,
            },
        )
        .map_err(|error| format!("Surge movement: {error}"))?;
    let pressure_before = surged.players[0].pressure;
    control.step();
    surged.step();
    let pressure_after = surged.players[0].pressure;
    let surge_event_amount = event(&surged, EventKind::Surge, Some(surged_unit))
        .map(|item| item.amount)
        .ok_or_else(|| "Surge activation emitted no event".to_string())?;
    if pressure_before.saturating_sub(pressure_after) != SURGE_PRESSURE {
        return Err(format!(
            "Surge pressure cost mismatch: before={pressure_before}, after={pressure_after}, expected={SURGE_PRESSURE}"
        ));
    }
    let cooldown_after_activation = entity(&surged, surged_unit)?.surge_cooldown;
    for _ in 0..u64::from(SURGE_TICKS) {
        control.step();
        surged.step();
    }
    let control_pos = entity(&control, control_unit)?.pos;
    let surged_pos = entity(&surged, surged_unit)?.pos;
    let control_distance = control_pos.distance_sq(control_start);
    let surged_distance = surged_pos.distance_sq(surged_start);
    if surged_distance <= control_distance {
        return Err(format!(
            "Surge did not increase movement distance: control={control_distance}, surge={surged_distance}"
        ));
    }

    let mut fire_lock = base_world(4402, Faction::Union);
    let fire_unit = first_id(&fire_lock, 0, Kind::Hook)?;
    transform_entity(&mut fire_lock, fire_unit, Kind::Riveter, Pos::cell(40, 64))?;
    let fire_target = first_id(&fire_lock, 1, Kind::Wick)?;
    place_entity(&mut fire_lock, fire_target, Pos::cell(44, 64), Order::Idle)?;
    fire_lock.reset_fixture_origin()?;
    fire_lock
        .issue(
            0,
            Command::Surge {
                units: vec![fire_unit],
            },
        )
        .map_err(|error| format!("fire-lock Surge: {error}"))?;
    fire_lock
        .issue(
            0,
            Command::Attack {
                units: vec![fire_unit],
                target: fire_target,
            },
        )
        .map_err(|error| format!("fire-lock attack: {error}"))?;
    let activation_tick = fire_lock.tick;
    let mut shots_during_active = 0usize;
    let mut shots_after_active = 0usize;
    for _ in 0..=u64::from(SURGE_TICKS.saturating_add(SURGE_POST_ACTIVE_TICKS)) {
        fire_lock.step();
        let active = fire_lock.tick <= activation_tick.saturating_add(u64::from(SURGE_TICKS));
        let shots = fire_lock
            .events
            .iter()
            .filter(|item| item.kind == EventKind::Shot && item.entity == Some(fire_unit))
            .count();
        if active {
            shots_during_active += shots;
        } else {
            shots_after_active += shots;
        }
    }
    if shots_during_active != 0 || shots_after_active == 0 {
        return Err(format!(
            "Surge fire lock mismatch: active shots={shots_during_active}, post-active shots={shots_after_active}"
        ));
    }
    let replay = replay_evidence(&mut fire_lock, out, "surge-fire-lock-union.replay.json")?;
    Ok(json!({
        "status": "passed",
        "cost_pressure": pressure_before.saturating_sub(pressure_after),
        "surge_event_amount": surge_event_amount,
        "active_ticks": SURGE_TICKS,
        "cooldown_after_activation": cooldown_after_activation,
        "expected_cooldown": SURGE_COOLDOWN_TICKS,
        "control_distance_sq": control_distance,
        "surged_distance_sq": surged_distance,
        "shots_during_active": shots_during_active,
        "shots_after_active": shots_after_active,
        "replay": replay,
        "interpretation": "A paid Surge increases travel while preserving terrain effects and suppresses weapon output until the active timer ends.",
    }))
}

fn doctrine_research(out: &Path, faction: Faction, doctrine: Doctrine) -> Result<Value, String> {
    let seed = match (faction, doctrine) {
        (Faction::Union, Doctrine::Hauling) => 4501,
        (Faction::Assembly, Doctrine::FireControl) => 4502,
        _ => 4503,
    };
    let mut world = base_world(seed, faction);
    world.players[0].salvage = DOCTRINE_SALVAGE.saturating_add(180);
    world.players[0].pressure = DOCTRINE_PRESSURE.saturating_add(10);
    let hq = first_id(&world, 0, Kind::Headquarters)?;
    let worker = first_id(&world, 0, faction.worker())?;
    // Keep one normal worker queued so research can prove the queue is kept
    // but paused.  The tick-zero resource fixture is part of the replay
    // initial state; no out-of-band resource grant occurs after first input.
    world.reset_fixture_origin()?;
    issue_step(
        &mut world,
        0,
        Command::Train {
            building: hq,
            kind: faction.worker(),
        },
    )?;
    let queue_before = entity(&world, hq)?
        .queue
        .first()
        .map(|item| item.remaining)
        .ok_or_else(|| "HQ worker queue did not start".to_string())?;
    issue_step(
        &mut world,
        0,
        Command::Research {
            building: hq,
            doctrine,
        },
    )?;
    let started = event(&world, EventKind::ResearchStarted, Some(hq)).is_some();
    let research_after_start = world.players[0]
        .research
        .ok_or_else(|| "research command did not create active state".to_string())?;
    let queue_at_start = entity(&world, hq)?
        .queue
        .first()
        .map(|item| item.remaining)
        .ok_or_else(|| "worker queue disappeared when research started".to_string())?;
    for _ in 0..u64::from(SAVE_RESUME_TICKS) {
        world.step();
    }
    let queue_after_pause_window = entity(&world, hq)?
        .queue
        .first()
        .map(|item| item.remaining)
        .ok_or_else(|| "worker queue disappeared during research".to_string())?;
    if !started || queue_at_start != queue_after_pause_window {
        return Err(format!(
            "research worker pause mismatch: started={started}, queue_at_start={queue_at_start}, queue_after={queue_after_pause_window}"
        ));
    }
    let save = save_resume_evidence(
        &mut world,
        out,
        match faction {
            Faction::Union => "research-hauling-union.save.json",
            Faction::Assembly => "research-fire-control-assembly.save.json",
            Faction::Compact => "research-compact.save.json",
        },
    )?;
    let save_tick = world.tick;
    let completion_limit = u64::from(DOCTRINE_TICKS).saturating_add(30);
    step_until(&mut world, completion_limit, |current| {
        current.players[0].doctrine == Some(doctrine) && current.players[0].research.is_none()
    })?;
    if world.players[0].doctrine != Some(doctrine) {
        return Err(format!(
            "research completed with {:?}, expected {doctrine:?}",
            world.players[0].doctrine
        ));
    }
    let replay = replay_evidence(
        &mut world,
        out,
        match faction {
            Faction::Union => "research-hauling-union.replay.json",
            Faction::Assembly => "research-fire-control-assembly.replay.json",
            Faction::Compact => "research-compact.replay.json",
        },
    )?;
    Ok(json!({
        "status": "passed",
        "faction": format!("{faction:?}"),
        "doctrine": format!("{doctrine:?}"),
        "cost": {"salvage": DOCTRINE_SALVAGE, "pressure": DOCTRINE_PRESSURE},
        "research_ticks": DOCTRINE_TICKS,
        "started": started,
        "research_remaining_after_start": research_after_start.remaining,
        "worker_id": worker,
        "queue_remaining_before_research": queue_before,
        "queue_remaining_at_start": queue_at_start,
        "queue_remaining_after_pause_window": queue_after_pause_window,
        "save_resume": save,
        "save_resume_end_tick": save_tick,
        "completed_doctrine": format!("{:?}", world.players[0].doctrine),
        "replay": replay,
        "interpretation": "One finished HQ chooses one doctrine; the active research timer pauses worker production while preserving its queue, and completion survives save/resume/replay.",
    }))
}

fn crowd_128_benchmark(_out: &Path) -> Result<Value, String> {
    let mut world = base_world(4600, Faction::Union);
    world.players[0].cap = 1_000;
    world.players[1].cap = 1_000;
    world.players[0].crew = 120;
    world.players[1].crew = 122;

    let template0 = first_id(&world, 0, Kind::Hook)?;
    let template1 = first_id(&world, 1, Kind::Wick)?;
    let template0_entity = entity(&world, template0)?.clone();
    let template1_entity = entity(&world, template1)?.clone();

    // A prepared field is the bounded alternative to spending tens of
    // thousands of simulation ticks on 114 serial production jobs.  Every
    // inserted machine receives a stable unique ID; reset_fixture_origin()
    // raises the private allocator and captures this exact public state in
    // the replay origin after invariant validation.
    for id in 15..=71u32 {
        let position = if id == 15 {
            // Keep the target outside Loom range while the Loom deploys; it
            // is moved into range through a real command below.
            Pos::cell(90, 80)
        } else {
            Pos::cell(92 + ((id - 15) % 8) as i32, 88 + ((id - 15) / 8) as i32)
        };
        world.entities.push(combat_clone(
            &template0_entity,
            id,
            0,
            Kind::Riveter,
            position,
        ));
    }
    for id in 72..=128u32 {
        let kind = if id == 72 {
            Kind::Loom
        } else {
            Kind::Reedguard
        };
        let position = if id == 72 {
            Pos::cell(100, 80)
        } else {
            Pos::cell(100 + ((id - 72) % 8) as i32, 88 + ((id - 72) / 8) as i32)
        };
        world
            .entities
            .push(combat_clone(&template1_entity, id, 1, kind, position));
    }
    world.entities.sort_by_key(|item| item.id);
    world.reset_fixture_origin()?;
    if world.entities.len() != CROWD_ENTITY_COUNT {
        return Err(format!(
            "crowd fixture entity count mismatch: got {}, expected {CROWD_ENTITY_COUNT}",
            world.entities.len()
        ));
    }

    let combat0 = ids_for(&world, 0, Kind::Riveter);
    let mut combat1 = ids_for(&world, 1, Kind::Reedguard);
    combat1.extend(ids_for(&world, 1, Kind::Loom));
    combat1.sort_unstable();
    issue_step(
        &mut world,
        0,
        Command::Stop {
            units: combat0.clone(),
        },
    )?;
    issue_step(
        &mut world,
        1,
        Command::Stop {
            units: combat1.clone(),
        },
    )?;
    let loom = first_id(&world, 1, Kind::Loom)?;
    let target = combat0
        .first()
        .copied()
        .ok_or_else(|| "crowd fixture missing Riveter target".to_string())?;
    // The prepared entities are already in the combat pocket, except for the
    // target kept just outside range while the Loom deploys.  The following
    // commands create one live warning/impact path without moving the rest of
    // the crowd or using hidden targets.
    issue_step(&mut world, 1, Command::Deploy { units: vec![loom] })?;
    step_until(&mut world, TICK_HZ * 3, |current| {
        entity(current, loom).is_ok_and(|item| item.deployed)
    })?;
    issue_step(&mut world, 1, Command::Stop { units: vec![loom] })?;
    move_entity_to(&mut world, 0, target, Pos::cell(92, 80))?;
    issue_step(
        &mut world,
        1,
        Command::Attack {
            units: vec![loom],
            target,
        },
    )?;
    // A deployed Loom engages on its own; the isolated warning under
    // measurement is the next one it emits, inside one full cooldown.
    step_until(&mut world, 120, |current| {
        event(current, EventKind::ArtilleryWarning, Some(loom)).is_some()
    })
    .map_err(|_| "crowd Loom emitted no artillery warning within 120 ticks".to_string())?;
    // Once the isolated Loom warning has been observed, engage both armies
    // through ordinary Hold orders.  Excluding the Loom preserves its explicit
    // artillery order while the other machines acquire visible targets.
    // Idle machines engage on their own, so the pocket is already fighting
    // by now; the Hold orders name only the machines still alive.
    let living = |ids: &[u32], world: &World| -> Vec<u32> {
        ids.iter()
            .copied()
            .filter(|id| entity(world, *id).is_ok())
            .collect()
    };
    let combat0_living = living(&combat0, &world);
    let combat1_without_loom: Vec<u32> = living(&combat1, &world)
        .into_iter()
        .filter(|id| *id != loom)
        .collect();
    world
        .issue(
            0,
            Command::Hold {
                units: combat0_living,
            },
        )
        .map_err(|error| format!("crowd Union Hold: {error}"))?;
    world
        .issue(
            1,
            Command::Hold {
                units: combat1_without_loom,
            },
        )
        .map_err(|error| format!("crowd Assembly Hold: {error}"))?;
    let starting_entity_count = world.entities.len();
    world.step();
    let machine = machine_label();
    let mut samples = Vec::with_capacity(180);
    let mut total_shots = 0usize;
    let mut total_damage_events = 0usize;
    let mut total_death_events = 0usize;
    let mut artillery_warnings = 0usize;
    let mut artillery_shots = 0usize;
    let mut artillery_damage_events = 0usize;
    let start = Instant::now();
    let benchmark_ticks = 180u64;
    for _ in 0..benchmark_ticks {
        let tick_start = Instant::now();
        world.step();
        samples.push(tick_start.elapsed().as_nanos() as u64);
        for event in &world.events {
            match event.kind {
                EventKind::Shot => {
                    total_shots = total_shots.saturating_add(1);
                    if event.entity == Some(loom) {
                        artillery_shots = artillery_shots.saturating_add(1);
                    }
                }
                EventKind::Damage => {
                    total_damage_events = total_damage_events.saturating_add(1);
                    if event.other == Some(loom) {
                        artillery_damage_events = artillery_damage_events.saturating_add(1);
                    }
                }
                EventKind::Death => total_death_events = total_death_events.saturating_add(1),
                EventKind::ArtilleryWarning => {
                    artillery_warnings = artillery_warnings.saturating_add(1)
                }
                _ => {}
            }
        }
    }
    samples.sort_unstable();
    let p50 = percentile_ms(&samples, 50);
    let p95 = percentile_ms(&samples, 95);
    let p99 = percentile_ms(&samples, 99);
    let final_hash = world.state_hash();
    Ok(json!({
        "status": "passed",
        "starting_entity_count": starting_entity_count,
        "ending_entity_count": world.entities.len(),
        "combat_units": combat0.len() + combat1.len(),
        "combat_engaged": true,
        "artillery_machine": "Assembly Loom",
        "artillery_source_id": loom,
        "benchmark_ticks": benchmark_ticks,
        "elapsed_seconds": start.elapsed().as_secs_f64(),
        "machine": machine,
        "fixture": "public tick-zero entity clones with unique IDs, reset_fixture_origin, then normal Stop/Deploy/Attack commands",
        "tick_time_ms": {"p50": p50, "p95": p95, "p99": p99},
        "events_sampled": {"Shot": total_shots, "Damage": total_damage_events, "Death": total_death_events},
        "artillery_events_sampled": {"ArtilleryWarning": artillery_warnings, "Shot": artillery_shots, "Damage": artillery_damage_events},
        "final_hash": final_hash,
        "evidence_limits": "128-entity prepared fixture engaged through normal Hold orders, with one Loom warning/impact path and recorded casualties; this is a timing sample, not a maximum-army performance promise or minimum-hardware guarantee.",
    }))
}

fn combat_clone(template: &Entity, id: u32, owner: u8, kind: Kind, pos: Pos) -> Entity {
    let mut clone = template.clone();
    let content = spec(kind);
    clone.id = id;
    clone.owner = owner;
    clone.kind = kind;
    clone.pos = pos;
    clone.hp = content.health;
    clone.max_hp = content.health;
    clone.facing = if owner == 0 { 0 } else { 4 };
    clone.build_remaining = 0;
    clone.queue.clear();
    clone.deployed = false;
    clone.deploy_remaining = 0;
    clone.deploy_target = false;
    clone.formation = Formation::Compact;
    clone.surge_remaining = 0;
    clone.surge_cooldown = 0;
    clone.order = Order::Idle;
    clone.carried = 0;
    clone.carried_kind = None;
    clone.gather_ticks = 0;
    clone.attack_cooldown = 0;
    clone.path.clear();
    clone.path_index = 0;
    clone.path_target = None;
    clone.path_lane_revision = 0;
    clone.blocked_ticks = 0;
    clone.waypoints.clear();
    clone.rally = None;
    clone.builder = None;
    clone.last_seen = None;
    clone
}

fn percentile_ms(samples: &[u64], percentile: usize) -> f64 {
    if samples.is_empty() {
        return 0.0;
    }
    let index = samples.len().saturating_sub(1).saturating_mul(percentile) / 100;
    samples[index] as f64 / 1_000_000.0
}

fn machine_label() -> String {
    if let Ok(label) = std::env::var("BRINEWAKE_BENCH_MACHINE")
        && !label.trim().is_empty()
    {
        return label;
    }
    #[cfg(target_os = "macos")]
    if let Ok(output) = ProcessCommand::new("sysctl")
        .args(["-n", "hw.model"])
        .output()
        && output.status.success()
    {
        let model = String::from_utf8_lossy(&output.stdout).trim().to_string();
        if !model.is_empty() {
            return model;
        }
    }
    format!("{}-{}", std::env::consts::OS, std::env::consts::ARCH)
}
